### ISSUE TITLE
Doesn't work on GTK 3.20 systems

### ISSUE THREAD

**Issue by F1ynn** [B00merang-Project/Windows-Whistler#2]
Can go into more detail if necessary but many many things are broken due to the theming changes in the new GTK release.

**Comment by Elbullazul** [comment]
@F1ynn yes, we're aware of this problem. Because this theme is based on our XP themes, we want to port one XP theme and then adapt the rest to all of them, including this one. Porting is a long project, but we're confident it will be done in the fastest way possible. We'll notify you when all is ready

**Comment by Elbullazul** [comment]
in fact, I had some spare time today and ported it to 3.20 + , so you can use it now.

here it is running in unity 7.5 (GTK 3.20)
![virtualbox_ubuntu 16 10_15_11_2016_20_37_40](https://cloud.githubusercontent.com/assets/15310985/20331463/61e39302-ab73-11e6-9f3c-6168f2304028.png)

**Comment by F1ynn** [comment]
The updated version works amazing, thank you so much!
